# Generated by Django 5.2.7 on 2025-10-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_longanswerquestion_user_multiplechoicequestion_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortanswerquestion',
            name='correct_answer',
            field=models.TextField(max_length=200),
        ),
    ]
