# Generated by Django 5.2.7 on 2025-10-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_shortanswerquestion_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='long_answer_questions',
            field=models.ManyToManyField(to='main_app.longanswerquestion'),
        ),
        migrations.AddField(
            model_name='practicetest',
            name='mcq_questions',
            field=models.ManyToManyField(to='main_app.multiplechoicequestion'),
        ),
        migrations.AddField(
            model_name='practicetest',
            name='short_answer_questions',
            field=models.ManyToManyField(to='main_app.shortanswerquestion'),
        ),
    ]
