# Generated by Django 5.2.7 on 2025-10-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_practicetest_long_answer_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='title',
            field=models.CharField(default='Untitled Test', max_length=200),
        ),
    ]
