# Generated by Django 5.2.7 on 2025-10-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_practicetest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetest',
            name='long_answer_questions',
            field=models.ManyToManyField(blank=True, to='main_app.longanswerquestion'),
        ),
        migrations.AlterField(
            model_name='practicetest',
            name='mcq_questions',
            field=models.ManyToManyField(blank=True, to='main_app.multiplechoicequestion'),
        ),
        migrations.AlterField(
            model_name='practicetest',
            name='short_answer_questions',
            field=models.ManyToManyField(blank=True, to='main_app.shortanswerquestion'),
        ),
    ]
