# Generated by Django 5.2.7 on 2025-10-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_userresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='question_text',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
    ]
