# Generated by Django 5.2.7 on 2025-11-03 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_userattempt_userresponse_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='attempt_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.userattempt'),
        ),
    ]
