# Generated by Django 5.2.7 on 2025-11-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_userattempt_attempt_number_alter_userattempt_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
