# Generated by Django 5.2.7 on 2025-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_userresponse_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer',
            field=models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='option_a',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='option_b',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='option_c',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='option_d',
            field=models.TextField(max_length=255),
        ),
    ]
