# Generated by Django 5.2.7 on 2025-11-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_multiplechoicequestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
